// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://spenlucbjyyuqbrikrdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZW5sdWNianl5dXFicmlrcmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMDE0MDMsImV4cCI6MjA3OTY3NzQwM30.FYx7P8ULtwXcPf8wIioCDomqgV0_-aChV9E7MK8j3Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);